apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: finsocial
    app.kubernetes.io/instance: finsocial-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: finsocial
spec:
  selector:
    app: finsocial
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 5000
